import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import type { PageDocument, ThemeTokens } from "@productstudio/shared-types";
import { DEFAULT_THEME_TOKENS } from "@productstudio/shared-types";
import { PageRenderer, collectAssetIds } from "@productstudio/renderer";
import { generatePageCss } from "./css.js";

export interface ExportFile {
  path: string;
  content: string | Buffer;
}

export interface ExportBundle {
  files: ExportFile[];
  referencedAssetIds: string[];
}

export interface ExportContext {
  theme?: ThemeTokens;
  resolveAssetUrl?: (assetId: string) => string | null;
  assetContents?: Record<string, Buffer>;
}

export interface ExportTarget {
  id: string;
  generate(doc: PageDocument, ctx: ExportContext): Promise<ExportBundle>;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export const htmlExportTarget: ExportTarget = {
  id: "html",
  async generate(doc, ctx) {
    const theme = ctx.theme ?? DEFAULT_THEME_TOKENS;
    const markup = renderToStaticMarkup(
      createElement(PageRenderer, {
        document: doc,
        breakpoint: "desktop",
        isEditing: false,
        theme,
        resolveAssetUrl: ctx.resolveAssetUrl,
      }),
    );
    const css = generatePageCss(doc.root, theme);
    const assetIds = collectAssetIds(doc.root);
    const files: ExportFile[] = [
      {
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(doc.seo.title ?? doc.name)}</title>
${doc.seo.description ? `<meta name="description" content="${escapeHtml(doc.seo.description)}" />` : ""}
<link rel="stylesheet" href="assets/styles.css" />
</head>
<body>
${markup}
</body>
</html>
`,
      },
      { path: "assets/styles.css", content: css },
    ];

    for (const id of assetIds) {
      const buf = ctx.assetContents?.[id];
      if (buf) {
        files.push({ path: `assets/images/${id}`, content: buf });
      }
    }

    return { files, referencedAssetIds: assetIds };
  },
};

function toPascal(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join("");
}

export const reactExportTarget: ExportTarget = {
  id: "react",
  async generate(doc, ctx) {
    const theme = ctx.theme ?? DEFAULT_THEME_TOKENS;
    const markup = renderToStaticMarkup(
      createElement(PageRenderer, {
        document: doc,
        breakpoint: "desktop",
        isEditing: false,
        theme,
        resolveAssetUrl: ctx.resolveAssetUrl,
      }),
    );
    const css = generatePageCss(doc.root, theme);
    const componentName = toPascal(doc.name) || "Page";
    const assetIds = collectAssetIds(doc.root);

    const files: ExportFile[] = [
      {
        path: `${componentName}.tsx`,
        content: `import styles from './styles/${doc.slug === "/" ? "home" : doc.slug}.module.css';

/** Generated by ProductStudio — deterministic export from page JSON. */
export default function ${componentName}() {
  return (
    <div className={styles.root} dangerouslySetInnerHTML={{ __html: ${JSON.stringify(markup)} }} />
  );
}
`,
      },
      {
        path: `styles/${doc.slug === "/" ? "home" : doc.slug}.module.css`,
        content: `.root {}\n${css}`,
      },
    ];

    for (const id of assetIds) {
      const buf = ctx.assetContents?.[id];
      if (buf) files.push({ path: `assets/${id}`, content: buf });
    }

    return { files, referencedAssetIds: assetIds };
  },
};

const targets = new Map<string, ExportTarget>([
  [htmlExportTarget.id, htmlExportTarget],
  [reactExportTarget.id, reactExportTarget],
]);

export function getExportTarget(id: string): ExportTarget {
  const t = targets.get(id);
  if (!t) throw new Error(`Unknown export target: ${id}`);
  return t;
}
